"$schema" = 'https://starship.rs/config-schema.json'

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
ss_color_fg0 = '#fbf1c7'
ss_color_fg1 = '#ebdbb2'
ss_color_blue = '#458588'
ss_color_aqua = '#689d6a'
ss_color_green = '#56A14A'
ss_color_orange = '#d65d0e'
ss_color_purple = '#b16286'
ss_color_red = '#cc241d'
ss_color_yellow = '#d79921'
ss_color_cyan = '#52a1cb'

[os]
disabled = true

[username]
show_always = true
style_user = "bold fg:ss_color_green"

[character]
disabled = false
success_symbol = '[>](bold fg:ss_color_fg1)'
error_symbol = '[x](bold fg:ss_color_red)'
vimcmd_symbol = '[<](bold fg:ss_color_green)'
vimcmd_replace_one_symbol = '[<](bold fg:ss_color_purple)'
vimcmd_replace_symbol = '[<](bold fg:ss_color_purple)'
vimcmd_visual_symbol = '[<](bold fg:ss_color_yellow)'

[directory]
style = "bold fg:ss_color_yellow"

[status]
symbol = "[x](bold red) "

## git
[git_commit]
tag_symbol = " tag "

[git_branch]
symbol = ""
style = 'bold fg:ss_color_orange'

[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"
renamed = "»"
deleted = "x"
modified = "!"
stashed = ""
untracked = ""

## dev-related symbols
[aws]
symbol = "aws "

[azure]
symbol = "azure "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[gleam]
symbol = "gleam "

[golang]
symbol = "go "
style = "bold ss_color_cyan"

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "
style = "red bold"

[julia]
symbol = "julia "

[kotlin]
symbol = "kotlin "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ocaml "

[opa]
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unknown "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "perl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[quarto]
symbol = "quarto "

[raku]
symbol = "raku "

[ruby]
symbol = "ruby "

[rust]
symbol = "rust "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
